apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: 'https://releases.rancher.com/server-charts/stable'
    chart: rancher
    targetRevision: 2.8.4
    helm:
      valueFiles:
      - $values/rancher/values.yaml
  - repoURL: 'git@github.com:aleiner/argocd-apps.git'
    targetRevision: main
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: cattle-system
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
