apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: 'https://github.com/aleiner/argocd-apps.git'
    targetRevision: main
    path: apps/ingress
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system